name: Compose report nightly

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip
          sudo apt-get install -y --no-install-recommends \
            latexmk \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            python3-venv \
            python3-pip

      - name: Create venv and install Pygments
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip Pygments

      - name: Create Imagens directory
        run: |
          mkdir -p Relat√≥rio/Imagens

      - name: Run make compose
        run: |
          make compose || true
        env:
          CI: true
